# A descriptive name for your GitHub Actions workflow.
name: Retrieve Secret and Save to File

# --- Trigger ---
# This section defines when the workflow will run.
# In this case, it triggers on every push to the 'main' branch.
on:
  push:
    branches:
      - main

# --- Jobs ---
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # The 'build' job is the only job in this workflow.
  build:
    # --- Runner ---
    # Specifies the type of virtual machine to run the job on.
    # To use your self-hosted runner, you must use the 'self-hosted' label.
    # GitHub Actions will then look for an available runner with this label.
    runs-on: backend

    # --- Steps ---
    # A job contains a sequence of tasks called steps.
    # Steps can run commands, run setup tasks, or run an action in your repository,
    # a public repository, or an action published in a Docker registry.
    steps:
      # Step 1: Check out your repository's code
      # This is a standard first step that allows the workflow to access your repo's files.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Get secrets from GitHub Secrets and write to a file
      # This is the core step of the pipeline.
      - name: Create file from secrets
        # The 'run' keyword tells the job to execute a command on the runner.
        # We use a multi-line command to save all secrets.
        # The first 'echo' uses '>' to create and write to the file.
        # Subsequent 'echo' commands use '>>' to append to the file without overwriting it.
        run: |
          echo "PUBLISHABLEKEY=${{ secrets.PUBLISHABLEKEY }}" > secret.txt
          echo "SECRETKEY=${{ secrets.SECRETKEY }}" >> secret.txt
          echo "WEBHOOKSECRET=${{ secrets.WEBHOOKSECRET }}" >> secret.txt

      # Optional Step 3: Verify the file was created and show its content
      # This step lists the files and then prints the content of the new file.
      # This is useful for debugging to ensure all secrets were written.
      - name: Verify file creation and content
        run: |
          ls -l
          echo "--- Content of secret.txt ---"
          cat secret.txt
